ESM module, dependencies upgrade
mifi/editly pull request #206
Opened 2022-08-22 09:30 UTC by wisekaa03

2022-08-23 08:03 UTC, mifi requested changes
Thanks for this PR! Looks good to me, except for a few small things.

Have you tested and it still works? Also is typescript still correct?

2022-08-23 08:16 UTC, mifi commented
Oh and we need to rewrite examples to ESM, as well as docs

2022-08-25 09:42 UTC, wisekaa03 commented on .eslintrc
> +  "import/extensions": [],
It's for "Unexpected use of file extension "js" for ..."
Maybe you want a
```
 "import/extensions": [".js"],
```

2022-08-25 09:45 UTC, wisekaa03 commented on cli.js
> +    params = json5.parse(readFileSync(json, 'utf-8'));
Ok

2022-08-25 09:46 UTC, wisekaa03 commented on package.json
> +  "version": "0.13.0",
I got it

2022-08-25 09:48 UTC, wisekaa03 commented on index.js
> +export const Editly = async (config = {}) => {
Ok

2022-08-25 10:00 UTC, wisekaa03 commented on audio.js
> +          ...lodash.flatMap(processedAudioLayers, ({ layerAudioPath }) => ['-i', layerAudioPath]),
Ok, but this was a lodash-es

2022-08-25 10:43 UTC, wisekaa03 commented
All is ok, with typescript.
I use wisekaa03/Editly with my commercial project.

2022-08-28 21:21 UTC, merged

2022-08-28 21:21 UTC, mifi commented
thanks! will publish a new version.